apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-xgb
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference-xgb
  template:
    metadata:
      labels:
        app: ml-inference-xgb
    spec:
      containers:
      - name: inference
        image: gcr.io/grad-phca/ml-inference:latest
        env:
        - name: MODEL_NAME
          value: "svm"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: MODEL_PATH
          value: "/models/models_additional"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
